### ISSUE TITLE
Strange constraint resolution behavior

### ISSUE THREAD

**Issue by txsmith** [clash-lang/ghc-typelits-natnormalise#18] opened 2018-06-08 19:27 UTC
First of all, thank you so much for the awesome work on this! I've been able to implement type-safe [bit fields](https://en.wikipedia.org/wiki/Bit_field) with this very nicely. However, in the process I've come across some quirks.

Normally, whenever I have a constraint that enforces: `a + b <= c`, the solver is able to derive that 
`a <= c - b` holds too.

Written in Haskell, this therefore compiles:
```haskell
example_good :: forall a b c. (a + b <= c) => ()
example_good = conclude (Proxy :: Proxy a) (Proxy :: Proxy b) (Proxy :: Proxy c)

conclude :: forall a b c. (a <= c - b) => Proxy a -> Proxy b -> Proxy c ->  ()
conclude _ _ _ = ()
```

But if we add an extra constraint something funny happens:
```haskell
example_bad :: forall a b c. (a + b <= c, b ~ 1) => ()
example_bad = conclude (Proxy :: Proxy a) (Proxy :: Proxy b) (Proxy :: Proxy c)
```

The compiler now produces this error:
```
• Could not deduce: (a <=? (c - 1)) ~ 'True
    arising from a use of ‘conclude’
  from the context: ((a + b) <= c, b ~ 1)
    bound by the type signature for:
               example_bad :: forall (a :: Nat) (b :: Nat) (c :: Nat).
                                ((a + b) <= c, b ~ 1) => ()
• In the expression: conclude (Proxy :: Proxy a) (Proxy :: Proxy b) (Proxy :: Proxy c)
  In an equation for ‘example_bad’
```

In my understaning, ensuring that `b ~ 1` should not change anything to the fact that if `a + b <= c` holds, then `a <= c - b` should hold too.

Furthermore the order in which the constraints get listed seems to matter for the outcome. While the above `example_bad` fails to compile, this version *does* compile:
```haskell
example_good' :: forall a b c. (b ~ 1, a + b <= c) => ()
example_good' = conclude (Proxy :: Proxy a) (Proxy :: Proxy b) (Proxy :: Proxy c)
```
Notice the `b ~ 1` and `a + b <= c` are now swapped.

What could cause this behavior? Is this even a problem with GHC.TypeLits.Normalise? Am I doing something wrong or have I run into some limitation? I hope someone can shed some light on this for me :)

**Comment by christiaanb** [comment] 2018-06-08 20:39
@txsmith I cannot reproduce with `master`, guess it's time to cut a new release.

**Comment by christiaanb** [comment] 2018-06-08 20:50
@txsmith What version of `ghc-typelits-natnormalise` are you currently using? because I cannot even get your `example_good` to compile with the latest version on hackage (0.6.1 released May 9th 2018)

**Comment by txsmith** [comment] 2018-06-08 22:10
I'm using 0.5.10 via Stackage LTS 11.12. 
Indeed as you say, with 0.6.1 both examples don't compile, but with `master` they do! I probably should have checked that earlier on... 

There's still one case where things don't work quite well but I suspect that this has nothing to do with `ghc-typelits-natnormalise`. I'll experiment a bit more tomorrow and will let you know.

**Comment by txsmith** [comment] 2018-06-09 09:59
There was a problem with the `singletons` in combination with the examples above. I just upgraded to the latest nightly snapshot with ghc 8.4 and now everything seems to work. Thanks your quick response by the way!

**Comment by christiaanb** [comment] 2018-08-18 10:15
Closing, as the issue seems solved

**Closed by christiaanb** 2018-08-18 10:15 UTC
